#
# Tim Monfette (tjm354)
# CS 361
# Makefile for Assignment 4
#

# Default is to compile
default: santa

# Compile Santa Claus code
santa:
	@mkdir ./santa_claus/bin
	@javac -d ./santa_claus/bin/ ./santa_claus/*.java

# Remove compiled code
clean:
	@rm -rf ./santa_claus/bin/
