#
# Tim Monfette (tjm354)
# CS 361
# Makefile for Assignment 3
#

# Default is to compile both
default: coolidge

# Compile Coolidge Bus code
coolidge:
	@mkdir ./coolidge_bus/bin
	@javac -d ./coolidge_bus/bin/ ./coolidge_bus/*.java

# Remove compiled code
clean:
	@rm -rf ./coolidge_bus/bin/
